name: code_text_field
description: A customizable code field supporting syntax highlighting
version: 1.0.0-5
homepage: https://github.com/BertrandBev/code_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0-nullsafety.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_keyboard_visibility: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
