name: code_text_field
description: A customizable code text field supporting syntax highlighting
version: 1.0.0
author: Bertrand Bevillard
homepage: https://github.com/BertrandBev/code_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.1.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
